#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 13 09:41:02 CEST 2021
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 3103f25d70d94cbbbe8087a05980999b --incr --debug typical --relax --mt 8 -L mat_mult_v1_00_a -L xil_defaultlib -L secureip --snapshot matrix_multiplier_bench_behav xil_defaultlib.matrix_multiplier_bench -log elaborate.log
